[package]
name = "rust-ts-mini-string-cache"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "3.3.0"
napi-derive = "3.2.5"
serde = "1.0.226"
serde_json = "1.0.145"
