/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MiniCache {
  constructor()
  add(key: string, value: string): boolean
  set(key: string, value: string): boolean
  get(key: string): string
  filter(keys: Array<string>): Array<CacheData>
  has(key: string): boolean
  delete(key: string): boolean
  all(): Array<CacheData>
}

export interface CacheData {
  key: string
  value: string
}
